name: Code Style

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - usage: actions/checkout@v3
      - name: Install PHP & dependencies
        run: composer install
      -name: Run PHP-CS-Fixer